- name: Deploy Maven Artifact
  hosts: localhost
  become: yes
  tasks:
    - name: Copy the artifact to the deployment directory
      ansible.builtin.copy:
        src: "/var/lib/jenkins/workspace/hellomaven-ci/target/hellomaven-ci-1.0-SNAPSHOT.jar"
        dest: "/opt/deployment/HelloMaven.jar"
